[workspace]

# Without resolver = "2", it seems that sometimes features get enabled
# in the guest based on features required by build dependencies.  If
# resolver = "2" causes other problems, this may need to be
# investigated further.
resolver = "2"

[package]
name = "risc0-zkvm-fault-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
risc0-zkvm = { path = "../..", default-features = false, features = [ "std", "fault" ] }
risc0-zkvm-fault = { path = "..", default-features = false }
rrs-lib = "0.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[profile.release]
lto = true
opt-level = 3
debug = 1

[package.metadata.release]
release = false
