[package]
name = "risc0-zkvm-fault-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../..", default-features = false, features = [ "std" ] }
rrs-lib = "0.1"
serde = "1.0"
