[package]
name = "risc0-zkvm-fault"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
env_logger = "0.10"
risc0-build = { workspace = true }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
